---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgDFxrWyFnhv0NS4YGDCjjMma5OQE9yeeDkFlb9kI9qrSQaSLGIXSC1iNdwPsHL/QksuTRdGlugmK553km8FO2Ulmd98zALT+uXsRD41dBF7FfmxwRbbkuMsF4UW3/UcIPJvR0KTIZe3XbRaBfFtLAcSyUs+SthGLtKqdeL5DIc2lKo00JwIwh3Os7PEhq8DK+eUtBMlLr0DAsqBAHebjKLlB6eujTWemlNRQntPx4XAcorCE/prq78Bk9XNoX2LKLM77Nlg7TbTw5qFq88ImuySiPJaaX+SUxeQMe+e4nN9ss9r4UtvKDKEECJthI+d3yQ1FgK8rAUXhzvjYrbp4j0fGSjPcOUUtu8DbOJvVTJeLwbMyetFoeEl1sf3kW0VGPlAlUtYn4NvBp6fyi2+m9HhyjmV1vwI+Dw1JdtcYGX9TUP+lynxD8fWj2VExU/r5v5eCpqIgzkkQmeG7TGW3OmU+BLMZ3oIqSf20MzND/ITjcFpPEpq8zq7tTwDlf+kL1u6gg6hZAPjmKkKahPcqjKao5192NUJQnUBzYJrbfvXx1vmF9Fc6U3jYrUfBDc9QwA4rmsl2d/Xp5sNK6JhEISerNURDsG7ZAg1JNJJF1zBPD+UGTkMfVv34r6Kt+cqUX/R0XQVGUIGTaAObActVBgT/cNnezA8zr3y/R2yL8zdzacTCdE1IrzGHBFii+K10ZvPIByx/x18JMhwiQz1aE0Ol+2D429xDd4YQeCJbHVeNJGjSfVcqCy2P+b3CQ==
  template:
    metadata:
      name: basic-auth
      namespace: longhorn-system
