---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rfc2136-tsig-secret
  namespace: external-dns
spec:
  encryptedData:
    TSIG_SECRET: AgBkTOFuyE7D69U9xReoqtbnlG0u3GC3kVI8s++vHmJ2fmCXc+f57WhivsVjfIHswG6BwaaEv/WdprFHBlRhkF5hZPDJDtokYNCaasTPie9kNSJTjiPgJvFtEqMhLBBjktyyNv6xq7V6Qguzb5LA8X3V93ImVG+GAT4w5BAkAX3UtxCSgnfL57lsOtsScYzKgcbRBhqkuocn3hoG29NTwfL+zMLi5a0AZ6D860KAExvqFII703bOqatZTaUEf2NYPJnjrbPTKsqfMA1X5yATIYUn/YgJcdb6WylDoighjfeBIGa1zCVHY0a754ptinBGJGb1gWJEm9PXzHTl5lvcaAZeldtLUJ1EeXcY27Q2GWYmyVDMc7yAfjThvB4T/MHs9Cf+67kOARi3CyljbcUoEDEdyQam9oYLXT14CYxaVjOWKVn4gIVUDOCc2jYN/wuxn0YJiDkpN/xoK2tAEn4IJmxWDI0Zvef3jNxt4QGcpe0kT/Wgy5C282uI0opJ/c3ZsGNeAjqBDUthgZEgGZ+nyVp95yxSUFDtmNSLLK+4qb8dVOr47SREdL6mRinO/s684lc/33AGZzmls50hjpYSRcTLVbEiP1KL500tD1u20bdx/LDk7AIDVPFr5OSLKJFb2yNOLsD/U9df9o4sxgtGK01GUhMsQFDrbgsEPdT8h/0UZ3Y+Odpq39SqlswGmrSImq3rr+a+ID9W+1VbxGG1DkrFdpXr0HeHsSchi3c+r41Qf7GeN+7XwTKlW6ekqw==
  template:
    metadata:
      name: rfc2136-tsig-secret
      namespace: external-dns
    type: Opaque
