---
kyverno:
  admissionController:
    replicas: 3
  backgroundController:
    replicas: 3
  cleanupController:
    replicas: 3
  reportsController:
    replicas: 3
  crds:
    migration:
      enabled: false
