---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:admission-controller:secrets
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
    argocd.argoproj.io/instance: kyverno
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:background-controller:secrets
  labels:
    rbac.kyverno.io/aggregate-to-background-controller: "true"  # Label für Background Controller
    argocd.argoproj.io/instance: kyverno-policies
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - delete
  - list
  - watch
